version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: debral
      POSTGRES_PASSWORD: 12481632
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://debral:12481632@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
